using System.Linq;
using Mbs.Numerics.Random;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using static System.FormattableString;

namespace Mbs.UnitTests.Numerics.RandomGenerators
{
    [TestClass]
    public class MersenneTwister11213BUniformRandomTests
    {
        private const int Seed = 12345;
        private const int Count = 5000;

        /// <summary>
        /// Taken from https://bitbucket.org/sergiu/random/src/.
        /// Verifies the value generated by the reference implementation after 10⁹ iterations.
        /// The generator is seeded using an array filled with 1s.
        /// </summary>
        [TestMethod]
        public void MersenneTwister11213BUniformRandom_NextUInt_BoostReferenceImplementationTest()
        {
            var gen = new MersenneTwister11213BUniformRandom(5489);
            for (int i = 0; i != 9999; ++i)
            {
                gen.NextUInt();
            }

            uint expected = 3809585648U;
            uint actual = gen.NextUInt();
            Assert.AreEqual(expected, actual,
                Invariant($"Boost (validate): actual={actual} expected={expected}"));

            gen.Reset();

            var expectedArray = new[] { 0xEF3F3F3FU, 0x70082175U, 0xDAF6EAF5U, 0x2A16A63EU };
            for (int i = 0; i != expectedArray.Length; ++i)
            {
                expected = expectedArray[i];
                actual = gen.NextUInt();
                Assert.AreEqual(expected, actual,
                    Invariant($"Boost (generate): index={i}, actual={actual} expected={expected}"));
            }
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_NextDouble_GeneratedMany_MeanHasCorrectValue()
        {
            var gen = new MersenneTwister11213BUniformRandom(Seed);
            double expected = 0.5;

            double actual = 0;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextDouble();
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-1,
                Invariant($"Mean value 1: actual={actual}, expected={expected}"));

            expected = 4;
            actual = 0;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextDouble(8);
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-2,
                Invariant($"Mean value 2: actual={actual}, expected={expected}"));

            expected = 6;
            actual = 0;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextDouble(4, 8);
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-2,
                Invariant($"Mean value 3: actual={actual}, expected={expected}"));
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_NextInt_GeneratedMany_MeanHasCorrectValue()
        {
            var gen = new MersenneTwister11213BUniformRandom(Seed);

            double expected = int.MaxValue / 2d;
            double actual = 0;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextInt();
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-1,
                Invariant($"Mean value 1: actual={actual}, expected={expected}"));

            expected = 400d;
            actual = 0d;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextInt(800);
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-2,
                Invariant($"Mean value 2: actual={actual}, expected={expected}"));

            expected = 600d;
            actual = 0d;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextInt(400, 800);
            }

            actual /= Count;
            Doubles.AreEqual(expected / actual, 1, 1e-2,
                Invariant($"Mean value 3: actual={actual}, expected={expected}"));
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_NextBoolean_GeneratedMany_MeanHasCorrectValue()
        {
            var gen = new MersenneTwister11213BUniformRandom(Seed);

            double expected = Count / 2d;
            double actual = 0;
            for (int i = 0; i < Count; ++i)
            {
                actual += gen.NextBoolean() ? 1 : 0;
            }

            Doubles.AreEqual(expected / actual, 1, 1e-1,
                Invariant($"Mean value: actual={actual}, expected={expected}"));
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_NextBytes_GeneratedMany_MeanHasCorrectValue()
        {
            var gen = new MersenneTwister11213BUniformRandom(Seed);

            double expected = 128;
            double actual = 0;
            var array = new byte[32];

            for (int i = 0; i < Count; ++i)
            {
                gen.NextBytes(array);
                actual = array.Aggregate(actual, (current, b) => current + b);
            }

            actual /= Count * 32;
            Doubles.AreEqual(expected / actual, 1, 1e-2,
                Invariant($"Mean value: actual={actual}, expected={expected}"));
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_Seed_SameSeed_SameValue()
        {
            var gen1 = new MersenneTwister11213BUniformRandom(Seed);
            int expected = gen1.NextInt();

            var gen2 = new MersenneTwister11213BUniformRandom(Seed);
            int actual = gen2.NextInt();

            Assert.AreEqual(expected, actual);
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_Seed_DifferentSeed_DifferentValue()
        {
            var gen1 = new MersenneTwister11213BUniformRandom(Seed);
            int expected = gen1.NextInt();

            var gen2 = new MersenneTwister11213BUniformRandom(Seed + 1);
            int actual = gen2.NextInt();

            Assert.AreNotEqual(expected, actual);
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_CanReset_ReturnsTrue()
        {
            var gen = new MersenneTwister11213BUniformRandom();

            Assert.IsTrue(gen.CanReset);
        }

        [TestMethod]
        public void MersenneTwister11213BUniformRandom_Reset_ValueGeneratedThenReset_SameValueGenerated()
        {
            var gen = new MersenneTwister11213BUniformRandom();
            int expected = gen.NextInt();

            gen.Reset();
            int actual = gen.NextInt();

            Assert.AreEqual(expected, actual);
        }
    }
}
