using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace Mbs.Trading.Markets
{
    /// <summary>
    /// ISO 10383 Market Identifier Code (MIC) utilities.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Generated automatically from the list of ISO 10383 Exchange/Market Identifier Codes, version SEP2017.1 (2017-09-29).
    /// </para>
    /// <para>
    /// See http://www.iso15022.org/MIC/homepageMIC.htm.
    /// </para>
    /// <para>
    /// Only the following countries are included:
    /// </para>
    /// <para>
    /// Austria, Belgium, Canada, Denmark, Finland, France, Germany, Iceland, Italy, Luxembourg, Norway, Portugal, Spain, Sweden, Switzerland, Netherlands, UnitedKingdom, UnitedStates, NoCountry.
    /// </para>
    /// </remarks>
    public sealed class Exchange
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Exchange" /> class.
        /// </summary>
        public Exchange()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Exchange" /> class.
        /// </summary>
        /// <param name="mic">The MIC.</param>
        public Exchange(ExchangeMic mic)
        {
            Mic = mic;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Exchange" /> class.
        /// </summary>
        /// <param name="euronextMic">The Euronext MIC.</param>
        public Exchange(EuronextMic euronextMic)
            : this(EuronextToMic(euronextMic))
        {
        }

        /// <summary>
        /// Gets or sets an ISO 10383 Market Identifier Code (MIC).
        /// </summary>
        [DataMember(IsRequired = true)]
        [DefaultValue(ExchangeMic.Xams)]
        public ExchangeMic Mic { get; set; } = ExchangeMic.Xams;

        /// <summary>
        /// Gets the time zone.
        /// </summary>
        public TimeSpan TimeZone
        {
            get
            {
                switch (Mic)
                {
                    // AT, Austria
                    case ExchangeMic.Egsi:
                    case ExchangeMic.Xwbo:
                    case ExchangeMic.Exaa:
                    case ExchangeMic.Wbah:
                    case ExchangeMic.Wbdm:
                    case ExchangeMic.Wbgf:
                    case ExchangeMic.Xvie:
                    // BE, Belgium
                    case ExchangeMic.Beam:
                    case ExchangeMic.Bmts:
                    case ExchangeMic.Mtsd:
                    case ExchangeMic.Mtsf:
                    case ExchangeMic.Blpx:
                    case ExchangeMic.Xbru:
                    case ExchangeMic.Alxb:
                    case ExchangeMic.Enxb:
                    case ExchangeMic.Mlxb:
                    case ExchangeMic.Tnlb:
                    case ExchangeMic.Vpxb:
                    case ExchangeMic.Xbrd:
                    // DK, Denmark
                    case ExchangeMic.Dasi:
                    case ExchangeMic.Dktc:
                    case ExchangeMic.Gxgr:
                    case ExchangeMic.Gxgf:
                    case ExchangeMic.Gxgm:
                    case ExchangeMic.Jbsi:
                    case ExchangeMic.Npga:
                    case ExchangeMic.Snsi:
                    case ExchangeMic.Xcse:
                    case ExchangeMic.Dcse:
                    case ExchangeMic.Fndk:
                    case ExchangeMic.Dndk:
                    case ExchangeMic.Mcse:
                    case ExchangeMic.Mndk:
                    // FR, France
                    case ExchangeMic.Coal:
                    case ExchangeMic.Epex:
                    case ExchangeMic.Exse:
                    case ExchangeMic.Fmts:
                    case ExchangeMic.Gmtf:
                    case ExchangeMic.Lchc:
                    case ExchangeMic.Natx:
                    case ExchangeMic.Xafr:
                    case ExchangeMic.Xbln:
                    case ExchangeMic.Xpar:
                    case ExchangeMic.Alxp:
                    case ExchangeMic.Mtch:
                    case ExchangeMic.Xmat:
                    case ExchangeMic.Xmli:
                    case ExchangeMic.Xmon:
                    case ExchangeMic.Xspm:
                    case ExchangeMic.Xpow:
                    case ExchangeMic.Xpsf:
                    case ExchangeMic.Xpot:
                    // DE, Germany
                    case ExchangeMic.X360T:
                    case ExchangeMic.Baad:
                    case ExchangeMic.Cats:
                    case ExchangeMic.Dapa:
                    case ExchangeMic.Dbox:
                    case ExchangeMic.Auto:
                    case ExchangeMic.Ecag:
                    case ExchangeMic.Ficx:
                    case ExchangeMic.Hsbt:
                    case ExchangeMic.Tgat:
                    case ExchangeMic.Xgat:
                    case ExchangeMic.Xgrm:
                    case ExchangeMic.Vwdx:
                    case ExchangeMic.Xber:
                    case ExchangeMic.Bera:
                    case ExchangeMic.Berb:
                    case ExchangeMic.Berc:
                    case ExchangeMic.Eqta:
                    case ExchangeMic.Eqtb:
                    case ExchangeMic.Eqtc:
                    case ExchangeMic.Eqtd:
                    case ExchangeMic.Xeqt:
                    case ExchangeMic.Zobx:
                    case ExchangeMic.Xdus:
                    case ExchangeMic.Dusa:
                    case ExchangeMic.Dusb:
                    case ExchangeMic.Dusc:
                    case ExchangeMic.Dusd:
                    case ExchangeMic.Xqtx:
                    case ExchangeMic.Xecb:
                    case ExchangeMic.Xecc:
                    case ExchangeMic.Xeee:
                    case ExchangeMic.Xeeo:
                    case ExchangeMic.Xeer:
                    case ExchangeMic.Xetr:
                    case ExchangeMic.Xeub:
                    case ExchangeMic.Xeta:
                    case ExchangeMic.Xetb:
                    case ExchangeMic.Xeup:
                    case ExchangeMic.Xeum:
                    case ExchangeMic.Xere:
                    case ExchangeMic.Xert:
                    case ExchangeMic.Xeur:
                    case ExchangeMic.Xfra:
                    case ExchangeMic.Fraa:
                    case ExchangeMic.Frab:
                    case ExchangeMic.Xdbc:
                    case ExchangeMic.Xdbv:
                    case ExchangeMic.Xdbx:
                    case ExchangeMic.Xham:
                    case ExchangeMic.Hama:
                    case ExchangeMic.Hamb:
                    case ExchangeMic.Hamm:
                    case ExchangeMic.Hamn:
                    case ExchangeMic.Haml:
                    case ExchangeMic.Xhan:
                    case ExchangeMic.Hana:
                    case ExchangeMic.Hanb:
                    case ExchangeMic.Xinv:
                    case ExchangeMic.Xmun:
                    case ExchangeMic.Muna:
                    case ExchangeMic.Munb:
                    case ExchangeMic.Mund:
                    case ExchangeMic.Munc:
                    case ExchangeMic.Xsco:
                    case ExchangeMic.Xsc1:
                    case ExchangeMic.Xsc2:
                    case ExchangeMic.Xsc3:
                    case ExchangeMic.Xstu:
                    case ExchangeMic.Euwx:
                    case ExchangeMic.Stua:
                    case ExchangeMic.Stub:
                    case ExchangeMic.Xstf:
                    case ExchangeMic.Stuc:
                    case ExchangeMic.Stud:
                    case ExchangeMic.Xxsc:
                    // IT, Italy
                    case ExchangeMic.Cgit:
                    case ExchangeMic.Cggd:
                    case ExchangeMic.Cgcm:
                    case ExchangeMic.Cgqt:
                    case ExchangeMic.Cgdb:
                    case ExchangeMic.Cgeb:
                    case ExchangeMic.Cgtr:
                    case ExchangeMic.Cgqd:
                    case ExchangeMic.Cgnd:
                    case ExchangeMic.Emid:
                    case ExchangeMic.Emdr:
                    case ExchangeMic.Emir:
                    case ExchangeMic.Emib:
                    case ExchangeMic.Etlx:
                    case ExchangeMic.Fbsi:
                    case ExchangeMic.Hmtf:
                    case ExchangeMic.Hmod:
                    case ExchangeMic.Hrfq:
                    case ExchangeMic.Mtso:
                    case ExchangeMic.Bond:
                    case ExchangeMic.Mtsc:
                    case ExchangeMic.Mtsm:
                    case ExchangeMic.Ssob:
                    case ExchangeMic.Xgme:
                    case ExchangeMic.Xmil:
                    case ExchangeMic.Mtah:
                    case ExchangeMic.Etfp:
                    case ExchangeMic.Mivx:
                    case ExchangeMic.Motx:
                    case ExchangeMic.Mtaa:
                    case ExchangeMic.Sedx:
                    case ExchangeMic.Xaim:
                    case ExchangeMic.Xdmi:
                    case ExchangeMic.Xmot:
                    // ES, Spain
                    case ExchangeMic.Bmex:
                    case ExchangeMic.Mabx:
                    case ExchangeMic.Send:
                    case ExchangeMic.Xbar:
                    case ExchangeMic.Xbil:
                    case ExchangeMic.Xdrf:
                    case ExchangeMic.Xlat:
                    case ExchangeMic.Xmad:
                    case ExchangeMic.Xmce:
                    case ExchangeMic.Xmrv:
                    case ExchangeMic.Xval:
                    case ExchangeMic.Merf:
                    case ExchangeMic.Xmpw:
                    case ExchangeMic.Marf:
                    case ExchangeMic.Bmcl:
                    case ExchangeMic.Sbar:
                    case ExchangeMic.Sbil:
                    case ExchangeMic.Bmea:
                    case ExchangeMic.Ibgh:
                    case ExchangeMic.Mibg:
                    case ExchangeMic.Omel:
                    case ExchangeMic.Pave:
                    case ExchangeMic.Xdpa:
                    case ExchangeMic.Xnaf:
                    // SE, Sweden
                    case ExchangeMic.Cryd:
                    case ExchangeMic.Cryx:
                    case ExchangeMic.Napa:
                    case ExchangeMic.Sebx:
                    case ExchangeMic.Ensx:
                    case ExchangeMic.Sebs:
                    case ExchangeMic.Xngm:
                    case ExchangeMic.Nmtf:
                    case ExchangeMic.Xndx:
                    case ExchangeMic.Xnmr:
                    case ExchangeMic.Xsat:
                    case ExchangeMic.Xsto:
                    case ExchangeMic.Fnse:
                    case ExchangeMic.Xopv:
                    case ExchangeMic.Csto:
                    case ExchangeMic.Dsto:
                    case ExchangeMic.Dnse:
                    case ExchangeMic.Msto:
                    case ExchangeMic.Mnse:
                    case ExchangeMic.Dked:
                    case ExchangeMic.Fied:
                    case ExchangeMic.Noed:
                    case ExchangeMic.Seed:
                    case ExchangeMic.Pned:
                    case ExchangeMic.Euwb:
                    case ExchangeMic.Uswb:
                    case ExchangeMic.Dkfi:
                    case ExchangeMic.Nofi:
                    case ExchangeMic.Ebon:
                    case ExchangeMic.Onse:
                    case ExchangeMic.Esto:
                    // CH, Switzerland
                    case ExchangeMic.Aixe:
                    case ExchangeMic.Dots:
                    case ExchangeMic.Ebss:
                    case ExchangeMic.Ebsc:
                    case ExchangeMic.Euch:
                    case ExchangeMic.Eusp:
                    case ExchangeMic.Eurm:
                    case ExchangeMic.Eusc:
                    case ExchangeMic.S3fm:
                    case ExchangeMic.Stox:
                    case ExchangeMic.Xscu:
                    case ExchangeMic.Xstv:
                    case ExchangeMic.Xstx:
                    case ExchangeMic.Ubsg:
                    case ExchangeMic.Ubsf:
                    case ExchangeMic.Ubsc:
                    case ExchangeMic.Vlex:
                    case ExchangeMic.Xbrn:
                    case ExchangeMic.Xswx:
                    case ExchangeMic.Xqmh:
                    case ExchangeMic.Xvtx:
                    case ExchangeMic.Xbtr:
                    case ExchangeMic.Xswm:
                    case ExchangeMic.Xsls:
                    case ExchangeMic.Xicb:
                    case ExchangeMic.Zkbx:
                    case ExchangeMic.Kmux:
                    // NL, The Netherlands
                    case ExchangeMic.Clmx:
                    case ExchangeMic.Hchc:
                    case ExchangeMic.Ndex:
                    case ExchangeMic.Imco:
                    case ExchangeMic.Imeq:
                    case ExchangeMic.Ndxs:
                    case ExchangeMic.Nlpx:
                    case ExchangeMic.Xams:
                    case ExchangeMic.Tnla:
                    case ExchangeMic.Xeuc:
                    case ExchangeMic.Xeue:
                    case ExchangeMic.Xeui:
                    case ExchangeMic.Xems:
                    case ExchangeMic.Xnxc:
                    // NO, Norway
                    case ExchangeMic.Fish:
                    case ExchangeMic.Fshx:
                    case ExchangeMic.Icas:
                    case ExchangeMic.Nexo:
                    case ExchangeMic.Nops:
                    case ExchangeMic.Norx:
                    case ExchangeMic.Eleu:
                    case ExchangeMic.Else:
                    case ExchangeMic.Elno:
                    case ExchangeMic.Eluk:
                    case ExchangeMic.Frei:
                    case ExchangeMic.Bulk:
                    case ExchangeMic.Stee:
                    case ExchangeMic.Nosc:
                    case ExchangeMic.Notc:
                    case ExchangeMic.Oslc:
                    case ExchangeMic.Xdnb:
                    case ExchangeMic.Xima:
                    case ExchangeMic.Xosl:
                    case ExchangeMic.Xoam:
                    case ExchangeMic.Xoas:
                    case ExchangeMic.Nibr:
                    case ExchangeMic.Merd:
                    case ExchangeMic.Merk:
                    case ExchangeMic.Xosc:
                    case ExchangeMic.Xoad:
                    case ExchangeMic.Xosd:
                    // LU, Luxembourg
                    case ExchangeMic.Cclx:
                    case ExchangeMic.Mibl:
                    case ExchangeMic.Rbcb:
                    case ExchangeMic.Rbsi:
                    case ExchangeMic.Xlux:
                    case ExchangeMic.Emtf:
                    case ExchangeMic.Xves:
                        return new TimeSpan(1, 0, 0);

                    // FI, Finland
                    case ExchangeMic.Fgex:
                    case ExchangeMic.Xhel:
                    case ExchangeMic.Fnfi:
                    case ExchangeMic.Dhel:
                    case ExchangeMic.Dnfi:
                    case ExchangeMic.Mhel:
                    case ExchangeMic.Mnfi:
                        return new TimeSpan(2, 0, 0);

                    // CA, Canada
                    case ExchangeMic.Cand:
                    case ExchangeMic.Canx:
                    case ExchangeMic.Chic:
                    case ExchangeMic.Xcx2:
                    case ExchangeMic.Cotc:
                    case ExchangeMic.Ifca:
                    case ExchangeMic.Ivzx:
                    case ExchangeMic.Lica:
                    case ExchangeMic.Matn:
                    case ExchangeMic.Neoe:
                    case ExchangeMic.Ngxc:
                    case ExchangeMic.Omga:
                    case ExchangeMic.Lynx:
                    case ExchangeMic.Tmxs:
                    case ExchangeMic.Xats:
                    case ExchangeMic.Xbbk:
                    case ExchangeMic.Xcnq:
                    case ExchangeMic.Pure:
                    case ExchangeMic.Xcxd:
                    case ExchangeMic.Xicx:
                    case ExchangeMic.Xmoc:
                    case ExchangeMic.Xmod:
                    case ExchangeMic.Xtse:
                    case ExchangeMic.Xtsx:
                    case ExchangeMic.Xtnx:
                    // US, United States
                    case ExchangeMic.Aats:
                    case ExchangeMic.Advt:
                    case ExchangeMic.Aqua:
                    case ExchangeMic.Atdf:
                    case ExchangeMic.Core:
                    case ExchangeMic.Baml:
                    case ExchangeMic.Mlvx:
                    case ExchangeMic.Mlco:
                    case ExchangeMic.Barx:
                    case ExchangeMic.Bard:
                    case ExchangeMic.Barl:
                    case ExchangeMic.Bcdx:
                    case ExchangeMic.Bats:
                    case ExchangeMic.Bato:
                    case ExchangeMic.Baty:
                    case ExchangeMic.Bzxd:
                    case ExchangeMic.Byxd:
                    case ExchangeMic.Bbsf:
                    case ExchangeMic.Bgcf:
                    case ExchangeMic.Fncs:
                    case ExchangeMic.Bgcd:
                    case ExchangeMic.Bhsf:
                    case ExchangeMic.Bids:
                    case ExchangeMic.Bltd:
                    case ExchangeMic.Bpol:
                    case ExchangeMic.Bnyc:
                    case ExchangeMic.Vtex:
                    case ExchangeMic.Nyfx:
                    case ExchangeMic.Btec:
                    case ExchangeMic.Icsu:
                    case ExchangeMic.Cded:
                    case ExchangeMic.Cgmi:
                    case ExchangeMic.Cicx:
                    case ExchangeMic.Lqfi:
                    case ExchangeMic.Cblc:
                    case ExchangeMic.Cmsf:
                    case ExchangeMic.Cred:
                    case ExchangeMic.Caes:
                    case ExchangeMic.Cslp:
                    case ExchangeMic.Dbsx:
                    case ExchangeMic.Deal:
                    case ExchangeMic.Edge:
                    case ExchangeMic.Eddp:
                    case ExchangeMic.Edga:
                    case ExchangeMic.Edgd:
                    case ExchangeMic.Edgx:
                    case ExchangeMic.Edgo:
                    case ExchangeMic.Egmt:
                    case ExchangeMic.Eris:
                    case ExchangeMic.Fast:
                    case ExchangeMic.Finr:
                    case ExchangeMic.Finn:
                    case ExchangeMic.Fino:
                    case ExchangeMic.Finy:
                    case ExchangeMic.Xadf:
                    case ExchangeMic.Ootc:
                    case ExchangeMic.Fsef:
                    case ExchangeMic.Fxal:
                    case ExchangeMic.Fxcm:
                    case ExchangeMic.G1xx:
                    case ExchangeMic.Gllc:
                    case ExchangeMic.Glps:
                    case ExchangeMic.Glpx:
                    case ExchangeMic.Gotc:
                    case ExchangeMic.Govx:
                    case ExchangeMic.Gree:
                    case ExchangeMic.Gsco:
                    case ExchangeMic.Sgmt:
                    case ExchangeMic.Gsef:
                    case ExchangeMic.Gtco:
                    case ExchangeMic.Gtsx:
                    case ExchangeMic.Gtxs:
                    case ExchangeMic.Hegx:
                    case ExchangeMic.Hppo:
                    case ExchangeMic.Hsfx:
                    case ExchangeMic.Icel:
                    case ExchangeMic.Iexg:
                    case ExchangeMic.Iexd:
                    case ExchangeMic.Ifus:
                    case ExchangeMic.Iepa:
                    case ExchangeMic.Imfx:
                    case ExchangeMic.Imag:
                    case ExchangeMic.Imbd:
                    case ExchangeMic.Imcr:
                    case ExchangeMic.Imen:
                    case ExchangeMic.Imir:
                    case ExchangeMic.Ifed:
                    case ExchangeMic.Imcg:
                    case ExchangeMic.Imcc:
                    case ExchangeMic.Ices:
                    case ExchangeMic.Imcs:
                    case ExchangeMic.Isda:
                    case ExchangeMic.Itgi:
                    case ExchangeMic.Jefx:
                    case ExchangeMic.Jlqd:
                    case ExchangeMic.Jpbx:
                    case ExchangeMic.Jpmx:
                    case ExchangeMic.Jses:
                    case ExchangeMic.Jsjx:
                    case ExchangeMic.Knig:
                    case ExchangeMic.Kncm:
                    case ExchangeMic.Knem:
                    case ExchangeMic.Knli:
                    case ExchangeMic.Knmx:
                    case ExchangeMic.Ackf:
                    case ExchangeMic.Lasf:
                    case ExchangeMic.Ledg:
                    case ExchangeMic.Levl:
                    case ExchangeMic.Lius:
                    case ExchangeMic.Lifi:
                    case ExchangeMic.Liuh:
                    case ExchangeMic.Lqed:
                    case ExchangeMic.Ltaa:
                    case ExchangeMic.Lmnx:
                    case ExchangeMic.Mihi:
                    case ExchangeMic.Xmio:
                    case ExchangeMic.Mprl:
                    case ExchangeMic.Msco:
                    case ExchangeMic.Mspl:
                    case ExchangeMic.Msrp:
                    case ExchangeMic.Mstx:
                    case ExchangeMic.Mslp:
                    case ExchangeMic.Mtus:
                    case ExchangeMic.Bvus:
                    case ExchangeMic.Mtsb:
                    case ExchangeMic.Mtxx:
                    case ExchangeMic.Mtxs:
                    case ExchangeMic.Mtxm:
                    case ExchangeMic.Mtxc:
                    case ExchangeMic.Mtxa:
                    case ExchangeMic.Nblx:
                    case ExchangeMic.Nfsc:
                    case ExchangeMic.Nfsa:
                    case ExchangeMic.Nfsd:
                    case ExchangeMic.Xstm:
                    case ExchangeMic.Nmra:
                    case ExchangeMic.Nodx:
                    case ExchangeMic.Nxus:
                    case ExchangeMic.Nypc:
                    case ExchangeMic.Ollc:
                    case ExchangeMic.Opra:
                    case ExchangeMic.Otcm:
                    case ExchangeMic.Otcb:
                    case ExchangeMic.Otcq:
                    case ExchangeMic.Pinc:
                    case ExchangeMic.Pini:
                    case ExchangeMic.Pinl:
                    case ExchangeMic.Pinx:
                    case ExchangeMic.Psgm:
                    case ExchangeMic.Cave:
                    case ExchangeMic.Pdqx:
                    case ExchangeMic.Pdqd:
                    case ExchangeMic.Pipe:
                    case ExchangeMic.Prse:
                    case ExchangeMic.Pulx:
                    case ExchangeMic.Ricx:
                    case ExchangeMic.Ricd:
                    case ExchangeMic.Scxs:
                    case ExchangeMic.Sgma:
                    case ExchangeMic.Shaw:
                    case ExchangeMic.Shad:
                    case ExchangeMic.Soho:
                    case ExchangeMic.Sstx:
                    case ExchangeMic.Tera:
                    case ExchangeMic.Tfsu:
                    case ExchangeMic.Them:
                    case ExchangeMic.Thre:
                    case ExchangeMic.Tmid:
                    case ExchangeMic.Tpse:
                    case ExchangeMic.Trck:
                    case ExchangeMic.Trux:
                    case ExchangeMic.Tru1:
                    case ExchangeMic.Tru2:
                    case ExchangeMic.Trwb:
                    case ExchangeMic.Bndd:
                    case ExchangeMic.Twsf:
                    case ExchangeMic.Dwsf:
                    case ExchangeMic.Tsad:
                    case ExchangeMic.Tsbx:
                    case ExchangeMic.Tsef:
                    case ExchangeMic.Ubsa:
                    case ExchangeMic.Ubsp:
                    case ExchangeMic.Vert:
                    case ExchangeMic.Vfcm:
                    case ExchangeMic.Virt:
                    case ExchangeMic.Weed:
                    case ExchangeMic.Xwee:
                    case ExchangeMic.Welx:
                    case ExchangeMic.Wsag:
                    case ExchangeMic.Xaqs:
                    case ExchangeMic.Xbox:
                    case ExchangeMic.Xcbo:
                    case ExchangeMic.C2Ox:
                    case ExchangeMic.Cbsx:
                    case ExchangeMic.Xcbf:
                    case ExchangeMic.Xcbt:
                    case ExchangeMic.Fcbt:
                    case ExchangeMic.Xkbt:
                    case ExchangeMic.Xcff:
                    case ExchangeMic.Xchi:
                    case ExchangeMic.Xcis:
                    case ExchangeMic.Xcme:
                    case ExchangeMic.Fcme:
                    case ExchangeMic.Glbx:
                    case ExchangeMic.Ximm:
                    case ExchangeMic.Xiom:
                    case ExchangeMic.Nyms:
                    case ExchangeMic.Cmes:
                    case ExchangeMic.Cbts:
                    case ExchangeMic.Cecs:
                    case ExchangeMic.Xcur:
                    case ExchangeMic.Xelx:
                    case ExchangeMic.Xfci:
                    case ExchangeMic.Xgmx:
                    case ExchangeMic.Xins:
                    case ExchangeMic.Iblx:
                    case ExchangeMic.Icbx:
                    case ExchangeMic.Icro:
                    case ExchangeMic.Iidx:
                    case ExchangeMic.Rcbx:
                    case ExchangeMic.Mocx:
                    case ExchangeMic.Xisx:
                    case ExchangeMic.Xisa:
                    case ExchangeMic.Xise:
                    case ExchangeMic.Mcry:
                    case ExchangeMic.Gmni:
                    case ExchangeMic.Xmer:
                    case ExchangeMic.Xmge:
                    case ExchangeMic.Xnas:
                    case ExchangeMic.Xbxo:
                    case ExchangeMic.Bosd:
                    case ExchangeMic.Nasd:
                    case ExchangeMic.Xbrt:
                    case ExchangeMic.Xncm:
                    case ExchangeMic.Xndq:
                    case ExchangeMic.Xngs:
                    case ExchangeMic.Xnim:
                    case ExchangeMic.Xnms:
                    case ExchangeMic.Xpbt:
                    case ExchangeMic.Xphl:
                    case ExchangeMic.Xpho:
                    case ExchangeMic.Xpor:
                    case ExchangeMic.Xpsx:
                    case ExchangeMic.Espd:
                    case ExchangeMic.Xbos:
                    case ExchangeMic.Xnym:
                    case ExchangeMic.Xcec:
                    case ExchangeMic.Xnye:
                    case ExchangeMic.Xnyl:
                    case ExchangeMic.Xnys:
                    case ExchangeMic.Aldp:
                    case ExchangeMic.Amxo:
                    case ExchangeMic.Arcd:
                    case ExchangeMic.Arco:
                    case ExchangeMic.Arcx:
                    case ExchangeMic.Nysd:
                    case ExchangeMic.Xase:
                    case ExchangeMic.Xnli:
                    case ExchangeMic.Xoch:
                    case ExchangeMic.Xotc:
                    case ExchangeMic.Xsef:
                        return new TimeSpan(-5, 0, 0);

                    // GB, United Kingdom
                    case ExchangeMic.X3579:
                    case ExchangeMic.Afdl:
                    case ExchangeMic.Ampx:
                    case ExchangeMic.Anzl:
                    case ExchangeMic.Aqxe:
                    case ExchangeMic.Arax:
                    case ExchangeMic.Atlb:
                    case ExchangeMic.Autx:
                    case ExchangeMic.Autp:
                    case ExchangeMic.Autb:
                    case ExchangeMic.Balt:
                    case ExchangeMic.Bltx:
                    case ExchangeMic.Bapa:
                    case ExchangeMic.Bcrm:
                    case ExchangeMic.Baro:
                    case ExchangeMic.Bark:
                    case ExchangeMic.Bart:
                    case ExchangeMic.Bcxe:
                    case ExchangeMic.Bate:
                    case ExchangeMic.Chix:
                    case ExchangeMic.Batd:
                    case ExchangeMic.Chid:
                    case ExchangeMic.Batf:
                    case ExchangeMic.Chio:
                    case ExchangeMic.Batp:
                    case ExchangeMic.Botc:
                    case ExchangeMic.Lisx:
                    case ExchangeMic.Bgci:
                    case ExchangeMic.Bgcb:
                    case ExchangeMic.Bkln:
                    case ExchangeMic.Bklf:
                    case ExchangeMic.Blox:
                    case ExchangeMic.Bmtf:
                    case ExchangeMic.Boat:
                    case ExchangeMic.Bosc:
                    case ExchangeMic.Brnx:
                    case ExchangeMic.Btee:
                    case ExchangeMic.Ebsm:
                    case ExchangeMic.Ebsd:
                    case ExchangeMic.Ebsi:
                    case ExchangeMic.Nexy:
                    case ExchangeMic.Ccml:
                    case ExchangeMic.Cco2:
                    case ExchangeMic.Cgme:
                    case ExchangeMic.Chev:
                    case ExchangeMic.Blnk:
                    case ExchangeMic.Cmee:
                    case ExchangeMic.Cmec:
                    case ExchangeMic.Cmed:
                    case ExchangeMic.Cmmt:
                    case ExchangeMic.Cryp:
                    case ExchangeMic.Cseu:
                    case ExchangeMic.Cscf:
                    case ExchangeMic.Csbx:
                    case ExchangeMic.Sics:
                    case ExchangeMic.Csin:
                    case ExchangeMic.Cssi:
                    case ExchangeMic.Dbes:
                    case ExchangeMic.Dbix:
                    case ExchangeMic.Dbdc:
                    case ExchangeMic.Dbcx:
                    case ExchangeMic.Dbcr:
                    case ExchangeMic.Dbmo:
                    case ExchangeMic.Dbse:
                    case ExchangeMic.Dowg:
                    case ExchangeMic.Echo:
                    case ExchangeMic.Embx:
                    case ExchangeMic.Encl:
                    case ExchangeMic.Eqld:
                    case ExchangeMic.Exeu:
                    case ExchangeMic.Exmp:
                    case ExchangeMic.Exor:
                    case ExchangeMic.Exvp:
                    case ExchangeMic.Exbo:
                    case ExchangeMic.Exlp:
                    case ExchangeMic.Exdc:
                    case ExchangeMic.Exsi:
                    case ExchangeMic.Excp:
                    case ExchangeMic.Exot:
                    case ExchangeMic.Fair:
                    case ExchangeMic.Fisu:
                    case ExchangeMic.Fxgb:
                    case ExchangeMic.Gemx:
                    case ExchangeMic.Gfic:
                    case ExchangeMic.Gfif:
                    case ExchangeMic.Gfin:
                    case ExchangeMic.Gfir:
                    case ExchangeMic.Gmeg:
                    case ExchangeMic.Xldx:
                    case ExchangeMic.Xgdx:
                    case ExchangeMic.Xgsx:
                    case ExchangeMic.Xgcx:
                    case ExchangeMic.Grif:
                    case ExchangeMic.Grio:
                    case ExchangeMic.Grse:
                    case ExchangeMic.Gsib:
                    case ExchangeMic.Bisi:
                    case ExchangeMic.Gsil:
                    case ExchangeMic.Gssi:
                    case ExchangeMic.Gsbx:
                    case ExchangeMic.Hpcs:
                    case ExchangeMic.Hsbc:
                    case ExchangeMic.Ibal:
                    case ExchangeMic.Icap:
                    case ExchangeMic.Icah:
                    case ExchangeMic.Icen:
                    case ExchangeMic.Icse:
                    case ExchangeMic.Ictq:
                    case ExchangeMic.Wclk:
                    case ExchangeMic.Igdl:
                    case ExchangeMic.Ifeu:
                    case ExchangeMic.Cxrt:
                    case ExchangeMic.Iflo:
                    case ExchangeMic.Ifll:
                    case ExchangeMic.Ifut:
                    case ExchangeMic.Iflx:
                    case ExchangeMic.Ifen:
                    case ExchangeMic.Cxot:
                    case ExchangeMic.Ifls:
                    case ExchangeMic.Inve:
                    case ExchangeMic.Iswa:
                    case ExchangeMic.Jpcb:
                    case ExchangeMic.Jpsi:
                    case ExchangeMic.Jssi:
                    case ExchangeMic.Kleu:
                    case ExchangeMic.Lcur:
                    case ExchangeMic.Liqu:
                    case ExchangeMic.Liqh:
                    case ExchangeMic.Liqf:
                    case ExchangeMic.Lmax:
                    case ExchangeMic.Lmad:
                    case ExchangeMic.Lmae:
                    case ExchangeMic.Lmaf:
                    case ExchangeMic.Lmao:
                    case ExchangeMic.Lmec:
                    case ExchangeMic.Lotc:
                    case ExchangeMic.Pldx:
                    case ExchangeMic.Lppm:
                    case ExchangeMic.Mael:
                    case ExchangeMic.Mcur:
                    case ExchangeMic.Mcxs:
                    case ExchangeMic.Mcxr:
                    case ExchangeMic.Mfgl:
                    case ExchangeMic.Mfxc:
                    case ExchangeMic.Mfxa:
                    case ExchangeMic.Mfxr:
                    case ExchangeMic.Mhip:
                    case ExchangeMic.Mlxn:
                    case ExchangeMic.Mlax:
                    case ExchangeMic.Mleu:
                    case ExchangeMic.Mlve:
                    case ExchangeMic.Msip:
                    case ExchangeMic.Mssi:
                    case ExchangeMic.Mufp:
                    case ExchangeMic.Muti:
                    case ExchangeMic.Mytr:
                    case ExchangeMic.N2Ex:
                    case ExchangeMic.Ndcm:
                    case ExchangeMic.Nexs:
                    case ExchangeMic.Nexx:
                    case ExchangeMic.Nexf:
                    case ExchangeMic.Nexg:
                    case ExchangeMic.Next:
                    case ExchangeMic.Nexn:
                    case ExchangeMic.Nexd:
                    case ExchangeMic.Nexl:
                    case ExchangeMic.Noff:
                    case ExchangeMic.Nosi:
                    case ExchangeMic.Nuro:
                    case ExchangeMic.Xnlx:
                    case ExchangeMic.Nurd:
                    case ExchangeMic.Nxeu:
                    case ExchangeMic.Otce:
                    case ExchangeMic.Peel:
                    case ExchangeMic.Xrsp:
                    case ExchangeMic.Xphx:
                    case ExchangeMic.Pieu:
                    case ExchangeMic.Pirm:
                    case ExchangeMic.Ppex:
                    case ExchangeMic.Qwix:
                    case ExchangeMic.Rbce:
                    case ExchangeMic.Rbct:
                    case ExchangeMic.Rtsi:
                    case ExchangeMic.Rbsx:
                    case ExchangeMic.Rtsl:
                    case ExchangeMic.Trfw:
                    case ExchangeMic.Tral:
                    case ExchangeMic.Secf:
                    case ExchangeMic.Sedr:
                    case ExchangeMic.Sgmx:
                    case ExchangeMic.Sgmy:
                    case ExchangeMic.Shar:
                    case ExchangeMic.Spec:
                    case ExchangeMic.Sprz:
                    case ExchangeMic.Ssex:
                    case ExchangeMic.Stal:
                    case ExchangeMic.Stan:
                    case ExchangeMic.Stsi:
                    case ExchangeMic.Swap:
                    case ExchangeMic.Tcml:
                    case ExchangeMic.Tfsv:
                    case ExchangeMic.Fxop:
                    case ExchangeMic.Tpie:
                    case ExchangeMic.Trax:
                    case ExchangeMic.Trde:
                    case ExchangeMic.Nave:
                    case ExchangeMic.Tcds:
                    case ExchangeMic.Trdx:
                    case ExchangeMic.Tfsg:
                    case ExchangeMic.Parx:
                    case ExchangeMic.Elix:
                    case ExchangeMic.Treu:
                    case ExchangeMic.Trea:
                    case ExchangeMic.Treo:
                    case ExchangeMic.Trqx:
                    case ExchangeMic.Trqm:
                    case ExchangeMic.Trqs:
                    case ExchangeMic.Trqa:
                    case ExchangeMic.Trsi:
                    case ExchangeMic.Ubsb:
                    case ExchangeMic.Ubsy:
                    case ExchangeMic.Ubsl:
                    case ExchangeMic.Ubse:
                    case ExchangeMic.Ubsi:
                    case ExchangeMic.Ukpx:
                    case ExchangeMic.Vcmo:
                    case ExchangeMic.Vega:
                    case ExchangeMic.Wins:
                    case ExchangeMic.Winx:
                    case ExchangeMic.Xalt:
                    case ExchangeMic.Xcor:
                    case ExchangeMic.Xgcl:
                    case ExchangeMic.Xlbm:
                    case ExchangeMic.Xlch:
                    case ExchangeMic.Xldn:
                    case ExchangeMic.Xsmp:
                    case ExchangeMic.Ensy:
                    case ExchangeMic.Xlme:
                    case ExchangeMic.Xlon:
                    case ExchangeMic.Aimx:
                    case ExchangeMic.Xlod:
                    case ExchangeMic.Xlom:
                    case ExchangeMic.Xmts:
                    case ExchangeMic.Hung:
                    case ExchangeMic.Ukgd:
                    case ExchangeMic.Amts:
                    case ExchangeMic.Emts:
                    case ExchangeMic.Gmts:
                    case ExchangeMic.Imts:
                    case ExchangeMic.Mczk:
                    case ExchangeMic.Mtsa:
                    case ExchangeMic.Mtsg:
                    case ExchangeMic.Mtss:
                    case ExchangeMic.Rmts:
                    case ExchangeMic.Smts:
                    case ExchangeMic.Vmts:
                    case ExchangeMic.Bvuk:
                    case ExchangeMic.Port:
                    case ExchangeMic.Mtsw:
                    case ExchangeMic.Xsga:
                    case ExchangeMic.Xswb:
                    case ExchangeMic.Xtup:
                    case ExchangeMic.Tpeq:
                    case ExchangeMic.Tben:
                    case ExchangeMic.Tbla:
                    case ExchangeMic.Tpcd:
                    case ExchangeMic.Tpfd:
                    case ExchangeMic.Tpre:
                    case ExchangeMic.Tpsd:
                    case ExchangeMic.Xtpe:
                    case ExchangeMic.Tpel:
                    case ExchangeMic.Tpsl:
                    case ExchangeMic.Xubs:
                    // IS, Iceland
                    case ExchangeMic.Xice:
                    case ExchangeMic.Dice:
                    case ExchangeMic.Fnis:
                    case ExchangeMic.Dnis:
                    case ExchangeMic.Mice:
                    case ExchangeMic.Mnis:
                    // PT, Portugal
                    case ExchangeMic.Omic:
                    case ExchangeMic.Opex:
                    case ExchangeMic.Omip:
                        return new TimeSpan(0, 0, 0);

                    // PT, Portugal
                    case ExchangeMic.Xlis:
                    case ExchangeMic.Alxl:
                    case ExchangeMic.Enxl:
                    case ExchangeMic.Mfox:
                    case ExchangeMic.Wqxl:
                        return new TimeSpan(1, 0, 0);

                    default:
                        return new TimeSpan(0L);
                }
            }
        }

        /// <summary>
        /// Gets a value indicating whether this exchange belongs to the Euronext family.
        /// </summary>
        public bool IsEuronext => IsEuronextMic(Mic);

        /// <summary>
        /// Gets the country.
        /// </summary>
        public ExchangeCountry Country
        {
            get
            {
                switch (Mic)
                {
                    case ExchangeMic.Egsi:
                    case ExchangeMic.Xwbo:
                    case ExchangeMic.Exaa:
                    case ExchangeMic.Wbah:
                    case ExchangeMic.Wbdm:
                    case ExchangeMic.Wbgf:
                    case ExchangeMic.Xvie:
                        return ExchangeCountry.Austria;
                    case ExchangeMic.Beam:
                    case ExchangeMic.Bmts:
                    case ExchangeMic.Mtsd:
                    case ExchangeMic.Mtsf:
                    case ExchangeMic.Blpx:
                    case ExchangeMic.Xbru:
                    case ExchangeMic.Alxb:
                    case ExchangeMic.Enxb:
                    case ExchangeMic.Mlxb:
                    case ExchangeMic.Tnlb:
                    case ExchangeMic.Vpxb:
                    case ExchangeMic.Xbrd:
                        return ExchangeCountry.Belgium;
                    case ExchangeMic.Cand:
                    case ExchangeMic.Canx:
                    case ExchangeMic.Chic:
                    case ExchangeMic.Xcx2:
                    case ExchangeMic.Cotc:
                    case ExchangeMic.Ifca:
                    case ExchangeMic.Ivzx:
                    case ExchangeMic.Lica:
                    case ExchangeMic.Matn:
                    case ExchangeMic.Neoe:
                    case ExchangeMic.Ngxc:
                    case ExchangeMic.Omga:
                    case ExchangeMic.Lynx:
                    case ExchangeMic.Tmxs:
                    case ExchangeMic.Xats:
                    case ExchangeMic.Xbbk:
                    case ExchangeMic.Xcnq:
                    case ExchangeMic.Pure:
                    case ExchangeMic.Xcxd:
                    case ExchangeMic.Xicx:
                    case ExchangeMic.Xmoc:
                    case ExchangeMic.Xmod:
                    case ExchangeMic.Xtse:
                    case ExchangeMic.Xtsx:
                    case ExchangeMic.Xtnx:
                        return ExchangeCountry.Canada;
                    case ExchangeMic.Dasi:
                    case ExchangeMic.Dktc:
                    case ExchangeMic.Gxgr:
                    case ExchangeMic.Gxgf:
                    case ExchangeMic.Gxgm:
                    case ExchangeMic.Jbsi:
                    case ExchangeMic.Npga:
                    case ExchangeMic.Snsi:
                    case ExchangeMic.Xcse:
                    case ExchangeMic.Dcse:
                    case ExchangeMic.Fndk:
                    case ExchangeMic.Dndk:
                    case ExchangeMic.Mcse:
                    case ExchangeMic.Mndk:
                        return ExchangeCountry.Denmark;
                    case ExchangeMic.Fgex:
                    case ExchangeMic.Xhel:
                    case ExchangeMic.Fnfi:
                    case ExchangeMic.Dhel:
                    case ExchangeMic.Dnfi:
                    case ExchangeMic.Mhel:
                    case ExchangeMic.Mnfi:
                        return ExchangeCountry.Finland;
                    case ExchangeMic.Coal:
                    case ExchangeMic.Epex:
                    case ExchangeMic.Exse:
                    case ExchangeMic.Fmts:
                    case ExchangeMic.Gmtf:
                    case ExchangeMic.Lchc:
                    case ExchangeMic.Natx:
                    case ExchangeMic.Xafr:
                    case ExchangeMic.Xbln:
                    case ExchangeMic.Xpar:
                    case ExchangeMic.Alxp:
                    case ExchangeMic.Mtch:
                    case ExchangeMic.Xmat:
                    case ExchangeMic.Xmli:
                    case ExchangeMic.Xmon:
                    case ExchangeMic.Xspm:
                    case ExchangeMic.Xpow:
                    case ExchangeMic.Xpsf:
                    case ExchangeMic.Xpot:
                        return ExchangeCountry.France;
                    case ExchangeMic.X360T:
                    case ExchangeMic.Baad:
                    case ExchangeMic.Cats:
                    case ExchangeMic.Dapa:
                    case ExchangeMic.Dbox:
                    case ExchangeMic.Auto:
                    case ExchangeMic.Ecag:
                    case ExchangeMic.Ficx:
                    case ExchangeMic.Hsbt:
                    case ExchangeMic.Tgat:
                    case ExchangeMic.Xgat:
                    case ExchangeMic.Xgrm:
                    case ExchangeMic.Vwdx:
                    case ExchangeMic.Xber:
                    case ExchangeMic.Bera:
                    case ExchangeMic.Berb:
                    case ExchangeMic.Berc:
                    case ExchangeMic.Eqta:
                    case ExchangeMic.Eqtb:
                    case ExchangeMic.Eqtc:
                    case ExchangeMic.Eqtd:
                    case ExchangeMic.Xeqt:
                    case ExchangeMic.Zobx:
                    case ExchangeMic.Xdus:
                    case ExchangeMic.Dusa:
                    case ExchangeMic.Dusb:
                    case ExchangeMic.Dusc:
                    case ExchangeMic.Dusd:
                    case ExchangeMic.Xqtx:
                    case ExchangeMic.Xecb:
                    case ExchangeMic.Xecc:
                    case ExchangeMic.Xeee:
                    case ExchangeMic.Xeeo:
                    case ExchangeMic.Xeer:
                    case ExchangeMic.Xetr:
                    case ExchangeMic.Xeub:
                    case ExchangeMic.Xeta:
                    case ExchangeMic.Xetb:
                    case ExchangeMic.Xeup:
                    case ExchangeMic.Xeum:
                    case ExchangeMic.Xere:
                    case ExchangeMic.Xert:
                    case ExchangeMic.Xeur:
                    case ExchangeMic.Xfra:
                    case ExchangeMic.Fraa:
                    case ExchangeMic.Frab:
                    case ExchangeMic.Xdbc:
                    case ExchangeMic.Xdbv:
                    case ExchangeMic.Xdbx:
                    case ExchangeMic.Xham:
                    case ExchangeMic.Hama:
                    case ExchangeMic.Hamb:
                    case ExchangeMic.Hamm:
                    case ExchangeMic.Hamn:
                    case ExchangeMic.Haml:
                    case ExchangeMic.Xhan:
                    case ExchangeMic.Hana:
                    case ExchangeMic.Hanb:
                    case ExchangeMic.Xinv:
                    case ExchangeMic.Xmun:
                    case ExchangeMic.Muna:
                    case ExchangeMic.Munb:
                    case ExchangeMic.Mund:
                    case ExchangeMic.Munc:
                    case ExchangeMic.Xsco:
                    case ExchangeMic.Xsc1:
                    case ExchangeMic.Xsc2:
                    case ExchangeMic.Xsc3:
                    case ExchangeMic.Xstu:
                    case ExchangeMic.Euwx:
                    case ExchangeMic.Stua:
                    case ExchangeMic.Stub:
                    case ExchangeMic.Xstf:
                    case ExchangeMic.Stuc:
                    case ExchangeMic.Stud:
                    case ExchangeMic.Xxsc:
                        return ExchangeCountry.Germany;
                    case ExchangeMic.Xice:
                    case ExchangeMic.Dice:
                    case ExchangeMic.Fnis:
                    case ExchangeMic.Dnis:
                    case ExchangeMic.Mice:
                    case ExchangeMic.Mnis:
                        return ExchangeCountry.Iceland;
                    case ExchangeMic.Cgit:
                    case ExchangeMic.Cggd:
                    case ExchangeMic.Cgcm:
                    case ExchangeMic.Cgqt:
                    case ExchangeMic.Cgdb:
                    case ExchangeMic.Cgeb:
                    case ExchangeMic.Cgtr:
                    case ExchangeMic.Cgqd:
                    case ExchangeMic.Cgnd:
                    case ExchangeMic.Emid:
                    case ExchangeMic.Emdr:
                    case ExchangeMic.Emir:
                    case ExchangeMic.Emib:
                    case ExchangeMic.Etlx:
                    case ExchangeMic.Fbsi:
                    case ExchangeMic.Hmtf:
                    case ExchangeMic.Hmod:
                    case ExchangeMic.Hrfq:
                    case ExchangeMic.Mtso:
                    case ExchangeMic.Bond:
                    case ExchangeMic.Mtsc:
                    case ExchangeMic.Mtsm:
                    case ExchangeMic.Ssob:
                    case ExchangeMic.Xgme:
                    case ExchangeMic.Xmil:
                    case ExchangeMic.Mtah:
                    case ExchangeMic.Etfp:
                    case ExchangeMic.Mivx:
                    case ExchangeMic.Motx:
                    case ExchangeMic.Mtaa:
                    case ExchangeMic.Sedx:
                    case ExchangeMic.Xaim:
                    case ExchangeMic.Xdmi:
                    case ExchangeMic.Xmot:
                        return ExchangeCountry.Italy;
                    case ExchangeMic.Cclx:
                    case ExchangeMic.Mibl:
                    case ExchangeMic.Rbcb:
                    case ExchangeMic.Rbsi:
                    case ExchangeMic.Xlux:
                    case ExchangeMic.Emtf:
                    case ExchangeMic.Xves:
                        return ExchangeCountry.Luxembourg;
                    case ExchangeMic.Fish:
                    case ExchangeMic.Fshx:
                    case ExchangeMic.Icas:
                    case ExchangeMic.Nexo:
                    case ExchangeMic.Nops:
                    case ExchangeMic.Norx:
                    case ExchangeMic.Eleu:
                    case ExchangeMic.Else:
                    case ExchangeMic.Elno:
                    case ExchangeMic.Eluk:
                    case ExchangeMic.Frei:
                    case ExchangeMic.Bulk:
                    case ExchangeMic.Stee:
                    case ExchangeMic.Nosc:
                    case ExchangeMic.Notc:
                    case ExchangeMic.Oslc:
                    case ExchangeMic.Xdnb:
                    case ExchangeMic.Xima:
                    case ExchangeMic.Xosl:
                    case ExchangeMic.Xoam:
                    case ExchangeMic.Xoas:
                    case ExchangeMic.Nibr:
                    case ExchangeMic.Merd:
                    case ExchangeMic.Merk:
                    case ExchangeMic.Xosc:
                    case ExchangeMic.Xoad:
                    case ExchangeMic.Xosd:
                        return ExchangeCountry.Norway;
                    case ExchangeMic.Omic:
                    case ExchangeMic.Opex:
                    case ExchangeMic.Xlis:
                    case ExchangeMic.Alxl:
                    case ExchangeMic.Enxl:
                    case ExchangeMic.Mfox:
                    case ExchangeMic.Omip:
                    case ExchangeMic.Wqxl:
                        return ExchangeCountry.Portugal;
                    case ExchangeMic.Bmex:
                    case ExchangeMic.Mabx:
                    case ExchangeMic.Send:
                    case ExchangeMic.Xbar:
                    case ExchangeMic.Xbil:
                    case ExchangeMic.Xdrf:
                    case ExchangeMic.Xlat:
                    case ExchangeMic.Xmad:
                    case ExchangeMic.Xmce:
                    case ExchangeMic.Xmrv:
                    case ExchangeMic.Xval:
                    case ExchangeMic.Merf:
                    case ExchangeMic.Xmpw:
                    case ExchangeMic.Marf:
                    case ExchangeMic.Bmcl:
                    case ExchangeMic.Sbar:
                    case ExchangeMic.Sbil:
                    case ExchangeMic.Bmea:
                    case ExchangeMic.Ibgh:
                    case ExchangeMic.Mibg:
                    case ExchangeMic.Omel:
                    case ExchangeMic.Pave:
                    case ExchangeMic.Xdpa:
                    case ExchangeMic.Xnaf:
                        return ExchangeCountry.Spain;
                    case ExchangeMic.Cryd:
                    case ExchangeMic.Cryx:
                    case ExchangeMic.Napa:
                    case ExchangeMic.Sebx:
                    case ExchangeMic.Ensx:
                    case ExchangeMic.Sebs:
                    case ExchangeMic.Xngm:
                    case ExchangeMic.Nmtf:
                    case ExchangeMic.Xndx:
                    case ExchangeMic.Xnmr:
                    case ExchangeMic.Xsat:
                    case ExchangeMic.Xsto:
                    case ExchangeMic.Fnse:
                    case ExchangeMic.Xopv:
                    case ExchangeMic.Csto:
                    case ExchangeMic.Dsto:
                    case ExchangeMic.Dnse:
                    case ExchangeMic.Msto:
                    case ExchangeMic.Mnse:
                    case ExchangeMic.Dked:
                    case ExchangeMic.Fied:
                    case ExchangeMic.Noed:
                    case ExchangeMic.Seed:
                    case ExchangeMic.Pned:
                    case ExchangeMic.Euwb:
                    case ExchangeMic.Uswb:
                    case ExchangeMic.Dkfi:
                    case ExchangeMic.Nofi:
                    case ExchangeMic.Ebon:
                    case ExchangeMic.Onse:
                    case ExchangeMic.Esto:
                        return ExchangeCountry.Sweden;
                    case ExchangeMic.Aixe:
                    case ExchangeMic.Dots:
                    case ExchangeMic.Ebss:
                    case ExchangeMic.Ebsc:
                    case ExchangeMic.Euch:
                    case ExchangeMic.Eusp:
                    case ExchangeMic.Eurm:
                    case ExchangeMic.Eusc:
                    case ExchangeMic.S3fm:
                    case ExchangeMic.Stox:
                    case ExchangeMic.Xscu:
                    case ExchangeMic.Xstv:
                    case ExchangeMic.Xstx:
                    case ExchangeMic.Ubsg:
                    case ExchangeMic.Ubsf:
                    case ExchangeMic.Ubsc:
                    case ExchangeMic.Vlex:
                    case ExchangeMic.Xbrn:
                    case ExchangeMic.Xswx:
                    case ExchangeMic.Xqmh:
                    case ExchangeMic.Xvtx:
                    case ExchangeMic.Xbtr:
                    case ExchangeMic.Xswm:
                    case ExchangeMic.Xsls:
                    case ExchangeMic.Xicb:
                    case ExchangeMic.Zkbx:
                    case ExchangeMic.Kmux:
                        return ExchangeCountry.Switzerland;
                    case ExchangeMic.Clmx:
                    case ExchangeMic.Hchc:
                    case ExchangeMic.Ndex:
                    case ExchangeMic.Imco:
                    case ExchangeMic.Imeq:
                    case ExchangeMic.Ndxs:
                    case ExchangeMic.Nlpx:
                    case ExchangeMic.Xams:
                    case ExchangeMic.Tnla:
                    case ExchangeMic.Xeuc:
                    case ExchangeMic.Xeue:
                    case ExchangeMic.Xeui:
                    case ExchangeMic.Xems:
                    case ExchangeMic.Xnxc:
                        return ExchangeCountry.Netherlands;
                    case ExchangeMic.X3579:
                    case ExchangeMic.Afdl:
                    case ExchangeMic.Ampx:
                    case ExchangeMic.Anzl:
                    case ExchangeMic.Aqxe:
                    case ExchangeMic.Arax:
                    case ExchangeMic.Atlb:
                    case ExchangeMic.Autx:
                    case ExchangeMic.Autp:
                    case ExchangeMic.Autb:
                    case ExchangeMic.Balt:
                    case ExchangeMic.Bltx:
                    case ExchangeMic.Bapa:
                    case ExchangeMic.Bcrm:
                    case ExchangeMic.Baro:
                    case ExchangeMic.Bark:
                    case ExchangeMic.Bart:
                    case ExchangeMic.Bcxe:
                    case ExchangeMic.Bate:
                    case ExchangeMic.Chix:
                    case ExchangeMic.Batd:
                    case ExchangeMic.Chid:
                    case ExchangeMic.Batf:
                    case ExchangeMic.Chio:
                    case ExchangeMic.Batp:
                    case ExchangeMic.Botc:
                    case ExchangeMic.Lisx:
                    case ExchangeMic.Bgci:
                    case ExchangeMic.Bgcb:
                    case ExchangeMic.Bkln:
                    case ExchangeMic.Bklf:
                    case ExchangeMic.Blox:
                    case ExchangeMic.Bmtf:
                    case ExchangeMic.Boat:
                    case ExchangeMic.Bosc:
                    case ExchangeMic.Brnx:
                    case ExchangeMic.Btee:
                    case ExchangeMic.Ebsm:
                    case ExchangeMic.Ebsd:
                    case ExchangeMic.Ebsi:
                    case ExchangeMic.Nexy:
                    case ExchangeMic.Ccml:
                    case ExchangeMic.Cco2:
                    case ExchangeMic.Cgme:
                    case ExchangeMic.Chev:
                    case ExchangeMic.Blnk:
                    case ExchangeMic.Cmee:
                    case ExchangeMic.Cmec:
                    case ExchangeMic.Cmed:
                    case ExchangeMic.Cmmt:
                    case ExchangeMic.Cryp:
                    case ExchangeMic.Cseu:
                    case ExchangeMic.Cscf:
                    case ExchangeMic.Csbx:
                    case ExchangeMic.Sics:
                    case ExchangeMic.Csin:
                    case ExchangeMic.Cssi:
                    case ExchangeMic.Dbes:
                    case ExchangeMic.Dbix:
                    case ExchangeMic.Dbdc:
                    case ExchangeMic.Dbcx:
                    case ExchangeMic.Dbcr:
                    case ExchangeMic.Dbmo:
                    case ExchangeMic.Dbse:
                    case ExchangeMic.Dowg:
                    case ExchangeMic.Echo:
                    case ExchangeMic.Embx:
                    case ExchangeMic.Encl:
                    case ExchangeMic.Eqld:
                    case ExchangeMic.Exeu:
                    case ExchangeMic.Exmp:
                    case ExchangeMic.Exor:
                    case ExchangeMic.Exvp:
                    case ExchangeMic.Exbo:
                    case ExchangeMic.Exlp:
                    case ExchangeMic.Exdc:
                    case ExchangeMic.Exsi:
                    case ExchangeMic.Excp:
                    case ExchangeMic.Exot:
                    case ExchangeMic.Fair:
                    case ExchangeMic.Fisu:
                    case ExchangeMic.Fxgb:
                    case ExchangeMic.Gemx:
                    case ExchangeMic.Gfic:
                    case ExchangeMic.Gfif:
                    case ExchangeMic.Gfin:
                    case ExchangeMic.Gfir:
                    case ExchangeMic.Gmeg:
                    case ExchangeMic.Xldx:
                    case ExchangeMic.Xgdx:
                    case ExchangeMic.Xgsx:
                    case ExchangeMic.Xgcx:
                    case ExchangeMic.Grif:
                    case ExchangeMic.Grio:
                    case ExchangeMic.Grse:
                    case ExchangeMic.Gsib:
                    case ExchangeMic.Bisi:
                    case ExchangeMic.Gsil:
                    case ExchangeMic.Gssi:
                    case ExchangeMic.Gsbx:
                    case ExchangeMic.Hpcs:
                    case ExchangeMic.Hsbc:
                    case ExchangeMic.Ibal:
                    case ExchangeMic.Icap:
                    case ExchangeMic.Icah:
                    case ExchangeMic.Icen:
                    case ExchangeMic.Icse:
                    case ExchangeMic.Ictq:
                    case ExchangeMic.Wclk:
                    case ExchangeMic.Igdl:
                    case ExchangeMic.Ifeu:
                    case ExchangeMic.Cxrt:
                    case ExchangeMic.Iflo:
                    case ExchangeMic.Ifll:
                    case ExchangeMic.Ifut:
                    case ExchangeMic.Iflx:
                    case ExchangeMic.Ifen:
                    case ExchangeMic.Cxot:
                    case ExchangeMic.Ifls:
                    case ExchangeMic.Inve:
                    case ExchangeMic.Iswa:
                    case ExchangeMic.Jpcb:
                    case ExchangeMic.Jpsi:
                    case ExchangeMic.Jssi:
                    case ExchangeMic.Kleu:
                    case ExchangeMic.Lcur:
                    case ExchangeMic.Liqu:
                    case ExchangeMic.Liqh:
                    case ExchangeMic.Liqf:
                    case ExchangeMic.Lmax:
                    case ExchangeMic.Lmad:
                    case ExchangeMic.Lmae:
                    case ExchangeMic.Lmaf:
                    case ExchangeMic.Lmao:
                    case ExchangeMic.Lmec:
                    case ExchangeMic.Lotc:
                    case ExchangeMic.Pldx:
                    case ExchangeMic.Lppm:
                    case ExchangeMic.Mael:
                    case ExchangeMic.Mcur:
                    case ExchangeMic.Mcxs:
                    case ExchangeMic.Mcxr:
                    case ExchangeMic.Mfgl:
                    case ExchangeMic.Mfxc:
                    case ExchangeMic.Mfxa:
                    case ExchangeMic.Mfxr:
                    case ExchangeMic.Mhip:
                    case ExchangeMic.Mlxn:
                    case ExchangeMic.Mlax:
                    case ExchangeMic.Mleu:
                    case ExchangeMic.Mlve:
                    case ExchangeMic.Msip:
                    case ExchangeMic.Mssi:
                    case ExchangeMic.Mufp:
                    case ExchangeMic.Muti:
                    case ExchangeMic.Mytr:
                    case ExchangeMic.N2Ex:
                    case ExchangeMic.Ndcm:
                    case ExchangeMic.Nexs:
                    case ExchangeMic.Nexx:
                    case ExchangeMic.Nexf:
                    case ExchangeMic.Nexg:
                    case ExchangeMic.Next:
                    case ExchangeMic.Nexn:
                    case ExchangeMic.Nexd:
                    case ExchangeMic.Nexl:
                    case ExchangeMic.Noff:
                    case ExchangeMic.Nosi:
                    case ExchangeMic.Nuro:
                    case ExchangeMic.Xnlx:
                    case ExchangeMic.Nurd:
                    case ExchangeMic.Nxeu:
                    case ExchangeMic.Otce:
                    case ExchangeMic.Peel:
                    case ExchangeMic.Xrsp:
                    case ExchangeMic.Xphx:
                    case ExchangeMic.Pieu:
                    case ExchangeMic.Pirm:
                    case ExchangeMic.Ppex:
                    case ExchangeMic.Qwix:
                    case ExchangeMic.Rbce:
                    case ExchangeMic.Rbct:
                    case ExchangeMic.Rtsi:
                    case ExchangeMic.Rbsx:
                    case ExchangeMic.Rtsl:
                    case ExchangeMic.Trfw:
                    case ExchangeMic.Tral:
                    case ExchangeMic.Secf:
                    case ExchangeMic.Sedr:
                    case ExchangeMic.Sgmx:
                    case ExchangeMic.Sgmy:
                    case ExchangeMic.Shar:
                    case ExchangeMic.Spec:
                    case ExchangeMic.Sprz:
                    case ExchangeMic.Ssex:
                    case ExchangeMic.Stal:
                    case ExchangeMic.Stan:
                    case ExchangeMic.Stsi:
                    case ExchangeMic.Swap:
                    case ExchangeMic.Tcml:
                    case ExchangeMic.Tfsv:
                    case ExchangeMic.Fxop:
                    case ExchangeMic.Tpie:
                    case ExchangeMic.Trax:
                    case ExchangeMic.Trde:
                    case ExchangeMic.Nave:
                    case ExchangeMic.Tcds:
                    case ExchangeMic.Trdx:
                    case ExchangeMic.Tfsg:
                    case ExchangeMic.Parx:
                    case ExchangeMic.Elix:
                    case ExchangeMic.Treu:
                    case ExchangeMic.Trea:
                    case ExchangeMic.Treo:
                    case ExchangeMic.Trqx:
                    case ExchangeMic.Trqm:
                    case ExchangeMic.Trqs:
                    case ExchangeMic.Trqa:
                    case ExchangeMic.Trsi:
                    case ExchangeMic.Ubsb:
                    case ExchangeMic.Ubsy:
                    case ExchangeMic.Ubsl:
                    case ExchangeMic.Ubse:
                    case ExchangeMic.Ubsi:
                    case ExchangeMic.Ukpx:
                    case ExchangeMic.Vcmo:
                    case ExchangeMic.Vega:
                    case ExchangeMic.Wins:
                    case ExchangeMic.Winx:
                    case ExchangeMic.Xalt:
                    case ExchangeMic.Xcor:
                    case ExchangeMic.Xgcl:
                    case ExchangeMic.Xlbm:
                    case ExchangeMic.Xlch:
                    case ExchangeMic.Xldn:
                    case ExchangeMic.Xsmp:
                    case ExchangeMic.Ensy:
                    case ExchangeMic.Xlme:
                    case ExchangeMic.Xlon:
                    case ExchangeMic.Aimx:
                    case ExchangeMic.Xlod:
                    case ExchangeMic.Xlom:
                    case ExchangeMic.Xmts:
                    case ExchangeMic.Hung:
                    case ExchangeMic.Ukgd:
                    case ExchangeMic.Amts:
                    case ExchangeMic.Emts:
                    case ExchangeMic.Gmts:
                    case ExchangeMic.Imts:
                    case ExchangeMic.Mczk:
                    case ExchangeMic.Mtsa:
                    case ExchangeMic.Mtsg:
                    case ExchangeMic.Mtss:
                    case ExchangeMic.Rmts:
                    case ExchangeMic.Smts:
                    case ExchangeMic.Vmts:
                    case ExchangeMic.Bvuk:
                    case ExchangeMic.Port:
                    case ExchangeMic.Mtsw:
                    case ExchangeMic.Xsga:
                    case ExchangeMic.Xswb:
                    case ExchangeMic.Xtup:
                    case ExchangeMic.Tpeq:
                    case ExchangeMic.Tben:
                    case ExchangeMic.Tbla:
                    case ExchangeMic.Tpcd:
                    case ExchangeMic.Tpfd:
                    case ExchangeMic.Tpre:
                    case ExchangeMic.Tpsd:
                    case ExchangeMic.Xtpe:
                    case ExchangeMic.Tpel:
                    case ExchangeMic.Tpsl:
                    case ExchangeMic.Xubs:
                        return ExchangeCountry.UnitedKingdom;
                    case ExchangeMic.Aats:
                    case ExchangeMic.Advt:
                    case ExchangeMic.Aqua:
                    case ExchangeMic.Atdf:
                    case ExchangeMic.Core:
                    case ExchangeMic.Baml:
                    case ExchangeMic.Mlvx:
                    case ExchangeMic.Mlco:
                    case ExchangeMic.Barx:
                    case ExchangeMic.Bard:
                    case ExchangeMic.Barl:
                    case ExchangeMic.Bcdx:
                    case ExchangeMic.Bats:
                    case ExchangeMic.Bato:
                    case ExchangeMic.Baty:
                    case ExchangeMic.Bzxd:
                    case ExchangeMic.Byxd:
                    case ExchangeMic.Bbsf:
                    case ExchangeMic.Bgcf:
                    case ExchangeMic.Fncs:
                    case ExchangeMic.Bgcd:
                    case ExchangeMic.Bhsf:
                    case ExchangeMic.Bids:
                    case ExchangeMic.Bltd:
                    case ExchangeMic.Bpol:
                    case ExchangeMic.Bnyc:
                    case ExchangeMic.Vtex:
                    case ExchangeMic.Nyfx:
                    case ExchangeMic.Btec:
                    case ExchangeMic.Icsu:
                    case ExchangeMic.Cded:
                    case ExchangeMic.Cgmi:
                    case ExchangeMic.Cicx:
                    case ExchangeMic.Lqfi:
                    case ExchangeMic.Cblc:
                    case ExchangeMic.Cmsf:
                    case ExchangeMic.Cred:
                    case ExchangeMic.Caes:
                    case ExchangeMic.Cslp:
                    case ExchangeMic.Dbsx:
                    case ExchangeMic.Deal:
                    case ExchangeMic.Edge:
                    case ExchangeMic.Eddp:
                    case ExchangeMic.Edga:
                    case ExchangeMic.Edgd:
                    case ExchangeMic.Edgx:
                    case ExchangeMic.Edgo:
                    case ExchangeMic.Egmt:
                    case ExchangeMic.Eris:
                    case ExchangeMic.Fast:
                    case ExchangeMic.Finr:
                    case ExchangeMic.Finn:
                    case ExchangeMic.Fino:
                    case ExchangeMic.Finy:
                    case ExchangeMic.Xadf:
                    case ExchangeMic.Ootc:
                    case ExchangeMic.Fsef:
                    case ExchangeMic.Fxal:
                    case ExchangeMic.Fxcm:
                    case ExchangeMic.G1xx:
                    case ExchangeMic.Gllc:
                    case ExchangeMic.Glps:
                    case ExchangeMic.Glpx:
                    case ExchangeMic.Gotc:
                    case ExchangeMic.Govx:
                    case ExchangeMic.Gree:
                    case ExchangeMic.Gsco:
                    case ExchangeMic.Sgmt:
                    case ExchangeMic.Gsef:
                    case ExchangeMic.Gtco:
                    case ExchangeMic.Gtsx:
                    case ExchangeMic.Gtxs:
                    case ExchangeMic.Hegx:
                    case ExchangeMic.Hppo:
                    case ExchangeMic.Hsfx:
                    case ExchangeMic.Icel:
                    case ExchangeMic.Iexg:
                    case ExchangeMic.Iexd:
                    case ExchangeMic.Ifus:
                    case ExchangeMic.Iepa:
                    case ExchangeMic.Imfx:
                    case ExchangeMic.Imag:
                    case ExchangeMic.Imbd:
                    case ExchangeMic.Imcr:
                    case ExchangeMic.Imen:
                    case ExchangeMic.Imir:
                    case ExchangeMic.Ifed:
                    case ExchangeMic.Imcg:
                    case ExchangeMic.Imcc:
                    case ExchangeMic.Ices:
                    case ExchangeMic.Imcs:
                    case ExchangeMic.Isda:
                    case ExchangeMic.Itgi:
                    case ExchangeMic.Jefx:
                    case ExchangeMic.Jlqd:
                    case ExchangeMic.Jpbx:
                    case ExchangeMic.Jpmx:
                    case ExchangeMic.Jses:
                    case ExchangeMic.Jsjx:
                    case ExchangeMic.Knig:
                    case ExchangeMic.Kncm:
                    case ExchangeMic.Knem:
                    case ExchangeMic.Knli:
                    case ExchangeMic.Knmx:
                    case ExchangeMic.Ackf:
                    case ExchangeMic.Lasf:
                    case ExchangeMic.Ledg:
                    case ExchangeMic.Levl:
                    case ExchangeMic.Lius:
                    case ExchangeMic.Lifi:
                    case ExchangeMic.Liuh:
                    case ExchangeMic.Lqed:
                    case ExchangeMic.Ltaa:
                    case ExchangeMic.Lmnx:
                    case ExchangeMic.Mihi:
                    case ExchangeMic.Xmio:
                    case ExchangeMic.Mprl:
                    case ExchangeMic.Msco:
                    case ExchangeMic.Mspl:
                    case ExchangeMic.Msrp:
                    case ExchangeMic.Mstx:
                    case ExchangeMic.Mslp:
                    case ExchangeMic.Mtus:
                    case ExchangeMic.Bvus:
                    case ExchangeMic.Mtsb:
                    case ExchangeMic.Mtxx:
                    case ExchangeMic.Mtxs:
                    case ExchangeMic.Mtxm:
                    case ExchangeMic.Mtxc:
                    case ExchangeMic.Mtxa:
                    case ExchangeMic.Nblx:
                    case ExchangeMic.Nfsc:
                    case ExchangeMic.Nfsa:
                    case ExchangeMic.Nfsd:
                    case ExchangeMic.Xstm:
                    case ExchangeMic.Nmra:
                    case ExchangeMic.Nodx:
                    case ExchangeMic.Nxus:
                    case ExchangeMic.Nypc:
                    case ExchangeMic.Ollc:
                    case ExchangeMic.Opra:
                    case ExchangeMic.Otcm:
                    case ExchangeMic.Otcb:
                    case ExchangeMic.Otcq:
                    case ExchangeMic.Pinc:
                    case ExchangeMic.Pini:
                    case ExchangeMic.Pinl:
                    case ExchangeMic.Pinx:
                    case ExchangeMic.Psgm:
                    case ExchangeMic.Cave:
                    case ExchangeMic.Pdqx:
                    case ExchangeMic.Pdqd:
                    case ExchangeMic.Pipe:
                    case ExchangeMic.Prse:
                    case ExchangeMic.Pulx:
                    case ExchangeMic.Ricx:
                    case ExchangeMic.Ricd:
                    case ExchangeMic.Scxs:
                    case ExchangeMic.Sgma:
                    case ExchangeMic.Shaw:
                    case ExchangeMic.Shad:
                    case ExchangeMic.Soho:
                    case ExchangeMic.Sstx:
                    case ExchangeMic.Tera:
                    case ExchangeMic.Tfsu:
                    case ExchangeMic.Them:
                    case ExchangeMic.Thre:
                    case ExchangeMic.Tmid:
                    case ExchangeMic.Tpse:
                    case ExchangeMic.Trck:
                    case ExchangeMic.Trux:
                    case ExchangeMic.Tru1:
                    case ExchangeMic.Tru2:
                    case ExchangeMic.Trwb:
                    case ExchangeMic.Bndd:
                    case ExchangeMic.Twsf:
                    case ExchangeMic.Dwsf:
                    case ExchangeMic.Tsad:
                    case ExchangeMic.Tsbx:
                    case ExchangeMic.Tsef:
                    case ExchangeMic.Ubsa:
                    case ExchangeMic.Ubsp:
                    case ExchangeMic.Vert:
                    case ExchangeMic.Vfcm:
                    case ExchangeMic.Virt:
                    case ExchangeMic.Weed:
                    case ExchangeMic.Xwee:
                    case ExchangeMic.Welx:
                    case ExchangeMic.Wsag:
                    case ExchangeMic.Xaqs:
                    case ExchangeMic.Xbox:
                    case ExchangeMic.Xcbo:
                    case ExchangeMic.C2Ox:
                    case ExchangeMic.Cbsx:
                    case ExchangeMic.Xcbf:
                    case ExchangeMic.Xcbt:
                    case ExchangeMic.Fcbt:
                    case ExchangeMic.Xkbt:
                    case ExchangeMic.Xcff:
                    case ExchangeMic.Xchi:
                    case ExchangeMic.Xcis:
                    case ExchangeMic.Xcme:
                    case ExchangeMic.Fcme:
                    case ExchangeMic.Glbx:
                    case ExchangeMic.Ximm:
                    case ExchangeMic.Xiom:
                    case ExchangeMic.Nyms:
                    case ExchangeMic.Cmes:
                    case ExchangeMic.Cbts:
                    case ExchangeMic.Cecs:
                    case ExchangeMic.Xcur:
                    case ExchangeMic.Xelx:
                    case ExchangeMic.Xfci:
                    case ExchangeMic.Xgmx:
                    case ExchangeMic.Xins:
                    case ExchangeMic.Iblx:
                    case ExchangeMic.Icbx:
                    case ExchangeMic.Icro:
                    case ExchangeMic.Iidx:
                    case ExchangeMic.Rcbx:
                    case ExchangeMic.Mocx:
                    case ExchangeMic.Xisx:
                    case ExchangeMic.Xisa:
                    case ExchangeMic.Xise:
                    case ExchangeMic.Mcry:
                    case ExchangeMic.Gmni:
                    case ExchangeMic.Xmer:
                    case ExchangeMic.Xmge:
                    case ExchangeMic.Xnas:
                    case ExchangeMic.Xbxo:
                    case ExchangeMic.Bosd:
                    case ExchangeMic.Nasd:
                    case ExchangeMic.Xbrt:
                    case ExchangeMic.Xncm:
                    case ExchangeMic.Xndq:
                    case ExchangeMic.Xngs:
                    case ExchangeMic.Xnim:
                    case ExchangeMic.Xnms:
                    case ExchangeMic.Xpbt:
                    case ExchangeMic.Xphl:
                    case ExchangeMic.Xpho:
                    case ExchangeMic.Xpor:
                    case ExchangeMic.Xpsx:
                    case ExchangeMic.Espd:
                    case ExchangeMic.Xbos:
                    case ExchangeMic.Xnym:
                    case ExchangeMic.Xcec:
                    case ExchangeMic.Xnye:
                    case ExchangeMic.Xnyl:
                    case ExchangeMic.Xnys:
                    case ExchangeMic.Aldp:
                    case ExchangeMic.Amxo:
                    case ExchangeMic.Arcd:
                    case ExchangeMic.Arco:
                    case ExchangeMic.Arcx:
                    case ExchangeMic.Nysd:
                    case ExchangeMic.Xase:
                    case ExchangeMic.Xnli:
                    case ExchangeMic.Xoch:
                    case ExchangeMic.Xotc:
                    case ExchangeMic.Xsef:
                        return ExchangeCountry.UnitedStates;
                    default:
                        return ExchangeCountry.NoCountry;
                }
            }
        }

        private static ExchangeMic EuronextToMic(EuronextMic euronextMic)
        {
            return euronextMic switch
            {
                EuronextMic.Xbru => ExchangeMic.Xbru,
                EuronextMic.Alxb => ExchangeMic.Alxb,
                EuronextMic.Enxb => ExchangeMic.Enxb,
                EuronextMic.Mlxb => ExchangeMic.Mlxb,
                EuronextMic.Tnlb => ExchangeMic.Tnlb,
                EuronextMic.Vpxb => ExchangeMic.Vpxb,
                EuronextMic.Xbrd => ExchangeMic.Xbrd,
                EuronextMic.Xpar => ExchangeMic.Xpar,
                EuronextMic.Alxp => ExchangeMic.Alxp,
                EuronextMic.Xmat => ExchangeMic.Xmat,
                EuronextMic.Xmli => ExchangeMic.Xmli,
                EuronextMic.Xmon => ExchangeMic.Xmon,
                EuronextMic.Xspm => ExchangeMic.Xspm,
                EuronextMic.Xlis => ExchangeMic.Xlis,
                EuronextMic.Alxl => ExchangeMic.Alxl,
                EuronextMic.Enxl => ExchangeMic.Enxl,
                EuronextMic.Mfox => ExchangeMic.Mfox,
                EuronextMic.Wqxl => ExchangeMic.Wqxl,
                EuronextMic.Xams => ExchangeMic.Xams,
                EuronextMic.Tnla => ExchangeMic.Tnla,
                EuronextMic.Xeuc => ExchangeMic.Xeuc,
                EuronextMic.Xeue => ExchangeMic.Xeue,
                EuronextMic.Xeui => ExchangeMic.Xeui,
                EuronextMic.Xldn => ExchangeMic.Xldn,
                EuronextMic.Xsmp => ExchangeMic.Xsmp,
                EuronextMic.Ensy => ExchangeMic.Ensy,
                _ => ExchangeMic.Xxxx
            };
        }

        private static bool IsEuronextMic(ExchangeMic mic)
        {
            switch (mic)
            {
                case ExchangeMic.Xbru:
                case ExchangeMic.Alxb:
                case ExchangeMic.Enxb:
                case ExchangeMic.Mlxb:
                case ExchangeMic.Tnlb:
                case ExchangeMic.Vpxb:
                case ExchangeMic.Xbrd:
                case ExchangeMic.Xpar:
                case ExchangeMic.Alxp:
                case ExchangeMic.Xmat:
                case ExchangeMic.Xmli:
                case ExchangeMic.Xmon:
                case ExchangeMic.Xspm:
                case ExchangeMic.Xlis:
                case ExchangeMic.Alxl:
                case ExchangeMic.Enxl:
                case ExchangeMic.Mfox:
                case ExchangeMic.Wqxl:
                case ExchangeMic.Xams:
                case ExchangeMic.Tnla:
                case ExchangeMic.Xeuc:
                case ExchangeMic.Xeue:
                case ExchangeMic.Xeui:
                case ExchangeMic.Xldn:
                case ExchangeMic.Xsmp:
                case ExchangeMic.Ensy:
                    return true;
                default:
                    return false;
            }
        }
    }
}
